version: '3.8'
services:
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jwt_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'

  app:
    image: jwt-auth:latest
    container_name: app
    restart: always
    environment:
      jwt_expiry: 18_000_000

    ports:
      - '1035:1035'