
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt-test
    username: jwt_test
    password: 123
  jpa:
    hibernate:
      ddl-auto: update


jwt:
  expiry: 18_000_000

server:
  port: 1035